name: Build and Release

on:
  push:
    tags:
      - "v*"

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: Upload frontend artifact
        uses: actions/upload-artifact@v3
        with:
          name: frontend-dist
          path: dist

  build-desktop:
    needs: build-frontend
    strategy:
      matrix:
        include:
          - os: windows-latest
            artifact_name: web-serial-debug-windows
            asset_name: web-serial-debug-windows.zip
          - os: macos-latest
            artifact_name: web-serial-debug-macos
            asset_name: web-serial-debug-macos.zip
          - os: ubuntu-latest
            artifact_name: web-serial-debug-linux
            asset_name: web-serial-debug-linux.zip

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Download frontend artifact
        uses: actions/download-artifact@v3
        with:
          name: frontend-dist
          path: go/dist

      - name: Build desktop app
        run: |
          cd go
          go build -v -o ${{ matrix.artifact_name }}

      - name: Create release asset
        run: |
          cd go
          zip -r ${{ matrix.asset_name }} ${{ matrix.artifact_name }} dist

      - name: Upload release asset
        uses: softprops/action-gh-release@v1
        with:
          files: go/${{ matrix.asset_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}